name: DevOps Quiz App CI/CD

on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'Dockerfile'
      - 'requirements.txt'
jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install python dependencies
        run: |
          pip install -r requirements.txt
      - name: test App (optional)
        run: |
          export PYTHONPATH=$(pwd)
          pytest
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_quiz_app:latest .

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/devops_quiz_app:latest ${{ secrets.DOCKER_USERNAME }}/devops_quiz_app:${{ github.sha }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops_quiz_app:${{ github.sha }}
